import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, temp }) {    
  return (
    <html lang="en">
      <body className={inter.className}>
        {temp}
        <h3>Root Layout</h3>
        {children}
        </body>
    </html>
  );
}